<?php
/**
 * Top menu for store
 *
 * @see JR_CleverCms_Block_Catalog_Navigation
 * @var $this JR_CleverCms_Block_Catalog_Navigation
 */
?>
<?php
$_categoriesIsFirst = !$this->showHomepageLink();
$_categoriesIsLast = !$this->hasCmsNavigationMenuPages();
$_cmsIsFirst = !$this->hasCategoriesNavigationMenuPages();

$_menu = $this->renderHomepageLinkHtml(0, false, true, 'level-top', '', $this->__("Home"));
$_menu.= $this->renderCategoriesMenuHtmlClever(0, $_categoriesIsLast, $_categoriesIsFirst, 'level-top');
$_menu.= $this->renderCmsMenuHtml(0, true, $_cmsIsFirst, 'level-top');
?>
<?php if ($_menu): ?>
<div class="nav-container">
    <ul id="nav">
        <?php echo $_menu ?>
    </ul>
</div>
<?php endif ?>
